### ISSUE TITLE
Could not install 0.8.0

### ISSUE THREAD

**Issue by mctep** [dotansimha/graphql-code-generator#126]
Hello! Thank you for your job.

I could not install the latest (0.8.0) version of the package:

```bash
$ node -v
v8.1.2

$ npm -v
5.3.0

$ npm i graphql-code-generator
npm ERR! path $(pwd)/node_modules/graphql-codegen-compiler/node_modules/graphql-codegen-core/dist/cli/gql-gen.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '$(pwd)/node_modules/graphql-codegen-compiler/node_modules/graphql-codegen-core/dist/cli/gql-gen.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by dotansimha** [comment]
Hi @mctep , any change you can try it with Node 7? 
Also, you installed it as global module, or local module?

**Comment by altschuler** [comment]
I've got node 7 and facing the same issue, with a global install.

**Comment by dotansimha** [comment]
@mctep @altschuler

It's actually an issue with `npm` installation, with `yarn` it works. 
Can you please try to install it with `yarn`?

**Comment by altschuler** [comment]
That was actually what I tried first, it installs without error, but gives `command not found: gql-gen` when running `gql-gen`. I've resorted to a local install and executing it with `$(yarn bin)/gql-gen`.

**Comment by dotansimha** [comment]
Fixed in `0.8.1` :)

**Comment by altschuler** [comment]
Haha, that was fast! It seems like it's not installing dependencies though (might be a problem on my end). Eg. `Error: Cannot find module 'graphql-tag'` and after installing that globally `Error: Cannot find module 'graphql/language/parser'`, etc.

**Comment by dotansimha** [comment]
@altschuler , yeah just noticed it. Can you please try `graphql-code-generator@0.9.0-alpha.1a4d72cb` (it's a canary version I am trying)

**Comment by altschuler** [comment]
That one seems to work!

**Comment by dotansimha** [comment]
@altschuler , I released it as a regular version, `0.8.2`, can you please try it as well?

**Comment by altschuler** [comment]
Yep, works as well :)

**Comment by dotansimha** [comment]
@altschuler thank you for your help :) It would be great to hear feedbacks regarding the new version, because I did a full refactor and implemented the whole package from scratch.

**Comment by altschuler** [comment]
@dotansimha see https://github.com/dotansimha/graphql-code-generator/issues/127 :P

**Comment by mctep** [comment]
Hello! I think it is still broken.

As I understand there is no `index.js` in package folder. Also no `main` section in `package.json`. So node could not require the package.

```
$ node
> require('graphql-code-generator')
Error: Cannot find module 'graphql-code-generator'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
>
```

```bash
$ ls node_modules/graphql-code-generator/index.js
ls: node_modules/graphql-code-generator/index.js: No such file or directory
$ cat node_modules/graphql-code-generator/package.json | grep main
(empty)
```

**Comment by dotansimha** [comment]
@mctep 
The `graphql-code-generator` shouldn't loaded directly using `require` because it's only a CLI executable (named `gql-gen`).
If you want to use the codegen programmatically, use the `graphql-codegen-compiler` package instead.

**Comment by mctep** [comment]
Oh. Yes. I've just imagined it. :) 
This package has been refactored 👍
