### ISSUE TITLE
TypeScript compaibility plugin issues with inline fragments since 1.1.1

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#1775]
**Describe the bug**
since typescript compatibility 1.1.1 we have the following issue. with 1.1.0 it works fine.

 → Cannot read property 'type' of undefined**

```
[17:24:49] Parse configuration [started]
[17:24:49] Parse configuration [completed]
[17:24:49] Generate outputs [started]
[17:24:49] Generate ./Scripts/shared/api/api.ts [started]
[17:24:49] Generate ./Scripts/shared/fragmentTypes.json [started]
[17:24:49] Load GraphQL schemas [started]
[17:24:49] Load GraphQL schemas [started]
[17:24:49] Load GraphQL schemas [completed]
[17:24:49] Load GraphQL schemas [completed]
[17:24:49] Load GraphQL documents [started]
[17:24:49] Load GraphQL documents [started]
[17:24:49] Load GraphQL documents [completed]
[17:24:49] Load GraphQL documents [completed]
[17:24:49] Generate [started]
[17:24:49] Generate [started]
[17:24:50] Generate [failed]
[17:24:50] → Cannot read property 'type' of undefined**
[17:24:50] Generate ./Scripts/shared/api/api.ts [failed]
[17:24:50] → Cannot read property 'type' of undefined**
[17:24:50] Generate [completed]
[17:24:50] Generate ./Scripts/shared/fragmentTypes.json [completed]
[17:24:50] Generate outputs [failed]
```

**To Reproduce**

graphql-codegen --config codegen.js

[schema.txt](https://github.com/dotansimha/graphql-code-generator/files/3121934/schema.txt)

2. My GraphQL operations:

```graphql
query fetchServerAnalyticsData($uid: String!) {
  process {
    servers(where: { uid: $uid }) {
      uid
      sources
      active
      principalName
      systemClass
      systemType
      getHostVirtualMachines {
        id
        uid
        host
        displayName
        storage
        sources
        vmType
        active
        vCenterName
        vmVersion
        dataCenterName
        collector
        monitoringGroup
      }
      imacs {
        ... on ServerChangeImac {
          __typename
          requestedAt
          mutatedBy
          mutationContext
          ticketNumber
          note
          active
          cIState
          customer
          patchWindow
          primaryOwner
          region
          systemClass
          businessModules
          description
          isVisibleToCustomer
          isManagedByGIA
          infrastructure
          serviceWindowPft
          serviceWindowApp
          comment
          investmentNumbers
          contractNumbers
          assetNumbers
          assignedServices
        }
        ... on ServerDecomImac {
          requestedAt
          ticketNumber
          mutatedBy
          mutationContext
          note
          __typename
        }
        ... on ServerSetupImac {
          mutatedBy
          mutationContext
          requestedAt
          ticketNumber
          note
          imacId
          archId
          currentState
          __typename
          backupPolicy
          explanation
          region
          description
          platformDistributionComment
          platformInstallComment
          satComment
          networkComment
          platformConfigComment
          serverType
          networkVlan
          hostname
          ip
          subnetMask
          defaultGateway
          vlan
          vlanId
          domain
          primaryDns
          secondaryDns
          computeCluster
          storageSystem
          passwordSaved
          customer
          patchWindow
          businessModules
          primaryOwner
          secondaryOwner
          requestedBy
          scomUser
          sccmUser
          scepUser
          scsmUser
          visionAppUser
          backupUser
          serverSize {
            name
            cpu
            memory
            disk
          }
          sla {
            application
            platform
          }
          systemClass
        }
      }
    }
  }
}

```

3. My `codegen.js` config file:

```yml
process.env.VERBOSE = true;
process.env.DEBUG = true;

module.exports = {
  schema: "intro.json",
  documents: ["Scripts/**/*.graphql"],
  config: {
    strict: true,
    namingConvention: {
      default: "change-case#pascalCase",
      enumValues: "change-case#upperCase"
    }
  },
  overwrite: true,
  generates: {
    "./Scripts/shared/api/api.ts": {
      config: {
        resolvers: false
      },
      plugins: ["typescript", "typescript-operations", "typescript-compatibility"]
    },
    "./Scripts/shared/fragmentTypes.json": {
      plugins: ["fragment-matcher"]
    }
  }
};

```

**Expected behavior**
no error while building and a api.ts file

**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.1.1
- NodeJS: v10.13.0

**Additional context**
excluding the grapqhl documents creates the api. it looks like the issue is in combination with the inline fragments.

**Comment by dotansimha** [comment]
Hi @OneCyrus , sorry for the delay. Fixed in https://github.com/dotansimha/graphql-code-generator/pull/1798

**Comment by dotansimha** [comment]
@OneCyrus Can you please try `1.1.2-alpha-76e69629.19`?

**Comment by OneCyrus** [comment]
it works again. thank you!

**Comment by OneCyrus** [comment]
ok. didn't fix it completely as we have some type issues now. it looks like the different fragments get assigned to the same types.

```
ERROR in ./Scripts/shared/api/api.ts(13166,7):
TS2344: Type '"region" | "active" | "description" | "customer" | "systemClass" | "assetNumbers" | "assignedServices" | "businessModules" | "comment" | "contractNumbers" | "infrastructure" | ... 13 more ... | "__typename"' does not satisfy the constraint '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
  Type '"region"' is not assignable to type '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
ERROR in ./Scripts/shared/api/api.ts(13223,7):
TS2344: Type '"region" | "description" | "customer" | "domain" | "systemClass" | "backupPolicy" | "businessModules" | "patchWindow" | "requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | ... 34 more ... | "__typename"' does not satisfy the constraint '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
  Type '"region"' is not assignable to type '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
ERROR in ./Scripts/shared/api/api.ts(13282,9):
TS2344: Type '"region" | "description" | "customer" | "domain" | "systemClass" | "backupPolicy" | "businessModules" | "patchWindow" | "requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | ... 34 more ... | "__typename"' does not satisfy the constraint '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
  Type '"region"' is not assignable to type '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
ERROR in ./Scripts/shared/api/api.ts(13342,9):
TS2344: Type '"region" | "description" | "customer" | "domain" | "systemClass" | "backupPolicy" | "businessModules" | "patchWindow" | "requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | ... 34 more ... | "__typename"' does not satisfy the constraint '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'.
  Type '"region"' is not assignable to type '"requestedAt" | "mutatedBy" | "mutationContext" | "ticketNumber" | "note" | "__typename"'
```

**Comment by dotansimha** [comment]
@OneCyrus I fixed another issue related to fragments, can you please try `1.1.2-alpha-6668a794.20`?

**Comment by OneCyrus** [comment]
we get closer but there are still two issues.

```
ERROR in ./Scripts/shared/api/api.ts(13208,8):
TS2339: Property 'serverSize' does not exist on type '({ __typename: "ServerChangeImac"; } & Pick<ServerChangeImac, "region" | "active" | "description" | "customer" | "systemClass" | "assetNumbers" | "assignedServices" | "businessModules" | ... 15 more ... | "primaryOwner">) | ({ ...; } & Pick<...>) | ({ ...; } & ... 1 more ... & { ...; })'.
ERROR in ./Scripts/shared/api/api.ts(13223,8):
TS2339: Property 'sla' does not exist on type '({ __typename: "ServerChangeImac"; } & Pick<ServerChangeImac, "region" | "active" | "description" | "customer" | "systemClass" | "assetNumbers" | "assignedServices" | "businessModules" | ... 15 more ... | "primaryOwner">) | ({ ...; } & Pick<...>) | ({ ...; } & ... 1 more ... & { ...; })'.
```
here's the generated ts-file:
[api.txt](https://github.com/dotansimha/graphql-code-generator/files/3134483/api.txt)

**Comment by dotansimha** [comment]
Thank you @OneCyrus , that's very helpful! 
I think I managed to fix this issue, can you please try `1.1.2-alpha-f498f076.22`?

**Comment by dotansimha** [comment]
@OneCyrus Can you please try `1.1.2-alpha-e801e53f.23`?

**Comment by OneCyrus** [comment]
it looks like that did the trick. thank you!

**Comment by dotansimha** [comment]
Awesome! Thank you for testing it, @OneCyrus ! 
I'm keeping it open to make it easier to track what should be included in the next version changelog.

**Comment by dotansimha** [comment]
Fixed in 1.1.3 🎉
