### ISSUE TITLE
enumPrefix = false applying to non-enum types

### ISSUE THREAD

**Issue by bmarker** [dotansimha/graphql-code-generator#7562]
**Describe the bug**
The enumPrefix = false config setting is stripping the prefix from non-enum types in `IResolversTypes` and `IResolversParentTypes`.

**To Reproduce**
https://codesandbox.io/s/quirky-proskuriakova-vmpz0v?file=/types.ts

1. My GraphQL schema:

```graphql
type Query {
    user: User!
}

type User {
    name: String!
}
```

2. My GraphQL operations:

None

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      typesPrefix: I
      enumPrefix: false
```

**Expected behavior**
Only skip the type prefix for enum types. The type for `User` should match the generated type `IUser`.
```
export type IResolversParentTypes = {
  Boolean: Scalars['Boolean'];
  Query: {};
  String: Scalars['String'];
  User: IUser;
};
```

Instead of:
```
export type IResolversParentTypes = {
  Boolean: Scalars['Boolean'];
  Query: {};
  String: Scalars['String'];
  User: User;
};
```

**Environment:**
https://codesandbox.io/s/quirky-proskuriakova-vmpz0v?file=/types.ts

```
    "@graphql-codegen/add": "^3.1.1",
    "@graphql-codegen/cli": "^2.4.0",
    "@graphql-codegen/typescript": "2.4.5",
    "@graphql-codegen/typescript-resolvers": "2.5.2",
    "graphql": "^16.2.0"
```

**Additional context**
Also happens with `typesSuffix` set and using `{T}` in `defaultMapper`.

**Comment by charlypoly** [comment]
Hi @bmarker,

Thank you for your report!


Could you please provide a reproduction on Codesandbox by using our template?
➡️ https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template/tree/master/

Thank you!

**Comment by bmarker** [comment]
There's already a Codesandbox link. Are you asking for a different format?

**Comment by charlypoly** [comment]
Hi @bmarker, you're right, I missed it.

I created a fix PR, could you try again with the following alpha versions?

```
@graphql-codegen/typescript-resolvers@2.5.3-alpha-643ff6c1d.0
@graphql-codegen/typescript@2.4.6-alpha-643ff6c1d.0
```

Thank you!

**Comment by bmarker** [comment]
It appears to be working in the sandbox. It will take me a bit longer to confirm for my full test case which had worked around the problem by setting models.

**Comment by charlypoly** [comment]
> It appears to be working in the sandbox. It will take me a bit longer to confirm for my full test case which had worked around the problem by setting models.

I did some local tests too and I did not see any regressions (+ CI tests)

**Comment by charlypoly** [comment]
Fixed in:

- `@graphql-codegen/typescript-resolvers@2.5.3`
- `@graphql-codegen/typescript@2.4.6`

**Comment by bmarker** [comment]
Confirmed for my real code that this fixes the internal mismatches in the generated types.

My full code requires setting a lot more model mappings if I remove `defaultMapper: unknown` so I have not resolved all the resolver mismatches but it worked for multiple resolvers.
