### ISSUE TITLE
Fetcher: graphql-request, got error "Type error: Cannot find module 'graphql-request/dist/types.dom' or its corresponding type  declarations."

### ISSUE THREAD

**Issue by barayuda** [dotansimha/graphql-code-generator#9046]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-operations, @graphql-codegen/typescript

### Describe the bug

I have trying to generate with script codegen.ts setup like below:
![image](https://user-images.githubusercontent.com/520463/220826860-30de7281-e8cb-4282-94fe-acf8060ab6e2.png)

And, when trying to build the project, I got an error like below:
![image](https://user-images.githubusercontent.com/520463/220826782-80b759d3-27c9-4dd1-8368-70591c3d1a67.png)

I used this version from my package.json
"graphql-request": "latest",
"@graphql-codegen/cli": "^3.2.0",
    "@graphql-codegen/client-preset": "^2.1.0",
    "@graphql-codegen/typed-document-node": "^3.0.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8",
    "@graphql-codegen/typescript-operations": "^3.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",
    
 ==========================
if I use version below:
"graphql-request": "5.1.0", // <-- only stick with this version

codegen working well.

### Your Example Website or App

sorry, internal project

### Steps to Reproduce the Bug or Issue

I have trying to generate with script codegen.ts setup like below:
![image](https://user-images.githubusercontent.com/520463/220826860-30de7281-e8cb-4282-94fe-acf8060ab6e2.png)

And, when trying to build the project, I got an error like below:
![image](https://user-images.githubusercontent.com/520463/220826782-80b759d3-27c9-4dd1-8368-70591c3d1a67.png)

I used this version from my package.json
"graphql-request": "latest",
"@graphql-codegen/cli": "^3.2.0",
    "@graphql-codegen/client-preset": "^2.1.0",
    "@graphql-codegen/typed-document-node": "^3.0.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8",
    "@graphql-codegen/typescript-operations": "^3.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",
    
 ==========================
if I use version below:
"graphql-request": "5.1.0", // <-- only stick with this version

codegen working well.

### Expected behavior

when generate the code from codegen, 

import { RequestInit } from 'graphql-request/dist/types.dom';

should generated:

import { RequestInit } from 'graphql-request/src/types.dom';

Because, the **dist** folder didn't generated on latest version of "graphql-request" (I mean [5.2.0-next.4](https://www.npmjs.com/package/graphql-request/v/5.2.0-next.4))

### Platform

- OS: Windows
- NodeJS: 16.19.0
- `graphql` version: 16.6.0
- 
"graphql-request": "latest",
"@graphql-codegen/cli": "^3.2.0",
    "@graphql-codegen/client-preset": "^2.1.0",
    "@graphql-codegen/typed-document-node": "^3.0.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8",
    "@graphql-codegen/typescript-operations": "^3.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",

### Codegen Config File

import type { CodegenConfig } from '@graphql-codegen/cli';
import { GRAPHQL_SCHEMA } from './src/constants/env';
const config: CodegenConfig = {
  overwrite: true,
  schema: GRAPHQL_SCHEMA,
  documents: ['./src/**/*.graphql'],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    './src/graphql/codegen/index.ts': {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-react-query',
      ],
      config: {
        interfacePrefix: 'I',
        typesPrefix: 'I',
        skipTypename: true,
        declarationKind: 'interface',
        noNamespaces: true,
        pureMagicComment: true,
        exposeQueryKeys: true,
        exposeFetcher: true,
        withHooks: true,
        fetcher: 'graphql-request',
      },
    },
  },
};

export default config;

**Comment by blaenk** [comment]
I am also experiencing this and I imagine anyone else would that uses 5.2.0 (happened to me by way of dependabot/renovate version bump).

**Comment by ramiel** [comment]
I can confirm the same issue. This happens with graphql-request version 5.2.0

**Comment by jdkajewski** [comment]
Ran into this yesterday afternoon as well. Currently pinned the `graphql-request` dependency to 5.1.0.

**Comment by alexdoan102** [comment]
ran into this also today.    the solution above => pinned the graphql-request dependency to 5.1.0. fixed the issue too

**Comment by jffry93** [comment]
Switching to 5.1.0 didn't do the trick. But going to an older version like 4.2.0 worked.

**Comment by geirsagberg** [comment]
Changing this to `import * as Dom from 'graphql-request/src/types.dom';` fixes it for me. I have to fix it every time I generate though.

**Comment by John-Colvin** [comment]
Workaround:

```
	hooks: {
		afterOneFileWrite: [
			'gsed -i -e"s|graphql-request/dist/types\.dom|graphql-request/src/types.dom|g"'
		]
	}
```

(`gsed` because I'm on a mac and homebrew and bleeurrgghhh just use normal `sed` if it supports `-i`. Or do something else to to do the find/replace operation).

**Comment by nbouvrette** [comment]
Unfortunately, the hook workaround didn't work for me adding this to my package.json did the trick:

`"generate": "graphql-codegen --config codegen.cjs && grep -rl  \"graphql-request/dist/types\" src/graphql | xargs sed -i '' 's|graphql-request/dist/types|graphql-request/src/types|g'"`

**Comment by punkratz312** [comment]
fyi, same issue here: 

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/8830888/230771451-0fb65511-69fd-4322-b92f-ba446aaba8d9.png">

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/8830888/230771468-365c2398-d93d-42ee-8cd8-1e84d87594c8.png">

thanks for working on it and happy easter 🐣

**Comment by yoanne2x** [comment]
having the same issues, tried the sed replacement and still get the same build error.
```
  "dependencies": {
    "graphql": "^16.6.0",
    "graphql-request": "^5.0.0"
  },
  "devDependencies": {
    "@games-workshop/eslint-config-lazarus": "^1.0.9",
    "@graphql-codegen/cli": "3.3.0",
    "@graphql-codegen/introspection": "3.0.1",
    "@graphql-codegen/typescript": "3.0.3",
    "@graphql-codegen/typescript-document-nodes": "3.0.3",
    "@graphql-codegen/typescript-graphql-files-modules": "2.2.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.9",
    "@graphql-codegen/typescript-msw": "^1.1.6",
    "@graphql-codegen/typescript-operations": "3.0.3",
    "@types/jest": "^27.4.1",
    "jest": "^27.5.1",
    "msw": "^0.39.2",
    "ts-jest": "^27.1.4",
    "typescript": "^4.5.4",
    "vite": "^2.9.0",
    "vite-plugin-dts": "^1.0.5"
  },```

**Comment by happyeric77** [comment]
Same issue here. Downgrading `graphql-request` to 5.1.0 works for me.

**Comment by mataspetrikas** [comment]
seeing the same problem with the `graphql-request` `6.0.0`

**Comment by LZL0** [comment]
Same issue.

**Comment by richardryangarcia** [comment]
Ran into this with graphql-request version 6.0.0 :( 

Any updates here? Thanks for the help!

**Comment by taranek** [comment]
Using `"graphql-request/build/esm/types.dom"` on `6.0.0` works for me, but that's still workaround

**Comment by malyzeli** [comment]
Issue in repository where the package is located:
https://github.com/dotansimha/graphql-code-generator-community/issues/331

Already resolved by opened pull request here:
https://github.com/dotansimha/graphql-code-generator-community/pull/335

**Comment by nbouvrette** [comment]
@malyzeli I don't know if this is a new issue or if this is already being covered, but when I updated to TypeScript `5.0.4` and graphql-request `6.0.0` instead of having to replace `import { RequestInit } from 'graphql-request/dist/types'` by `import { RequestInit } from 'graphql-request/src/types'`, now I need to remove the line completely.

It looks like `RequestInit` is no longer provided by `graphql-request` but directly part of the global TypeScript types in `node_modules/typescript/lib/lib.dom.d.ts`

**Comment by khanakia** [comment]
> hooks: {
> 		afterOneFileWrite: [
> 			'gsed -i -e"s|graphql-request/dist/types\.dom|graphql-request/src/types.dom|g"'
> 		]
> 	}

What file i should add this code ?

**Comment by beeman** [comment]
I worked around this by using the [add](https://the-guild.dev/graphql/codegen/plugins/other/add) plugin to add a `// @ts-nocheck` comment to the generated file.

```ts
const config: CodegenConfig = {
  overwrite: true,
  schema: './api-schema.graphql',
  documents: ['libs/graphql/**/*.graphql'],
  generates: {
    'apps/api-e2e/src/support/sdk/graphql-request.ts': {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-graphql-request',
        {
          add: {
            content: '// @ts-nocheck',
          },
        },
      ],
      config: {
        rawRequest: true,
      },
    },
  },
}
```

**Comment by nbouvrette** [comment]
> What file i should add this code ?

@khanakia you need to add the hook in your Codegen config (TypeScript doc [here](https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config) and hook doc [here](https://the-guild.dev/graphql/codegen/docs/config-reference/lifecycle-hooks))

One challenge that I face on the other hand is that I think that the generator checks for timestamps or has a cache so it will not always regenerate the files. To bypass that I added a global hook that deletes all generated files like this:

```ts
  hooks: {
    afterStart: ["find ./src/graphql -name '*.generated.*' -delete"],
  }
```

**Comment by beeman** [comment]
> > I worked around this by using the [add](https://the-guild.dev/graphql/codegen/plugins/other/add) plugin to add a `// @ts-nocheck` comment to the generated file.
> > ```ts
> > const config: CodegenConfig = {
> >   overwrite: true,
> >   schema: './api-schema.graphql',
> >   documents: ['libs/graphql/**/*.graphql'],
> >   generates: {
> >     'apps/api-e2e/src/support/sdk/graphql-request.ts': {
> >       plugins: [
> >         'typescript',
> >         'typescript-operations',
> >         'typescript-graphql-request',
> >         {
> >           add: {
> >             content: '// @ts-nocheck',
> >           },
> >         },
> >       ],
> >       config: {
> >         rawRequest: true,
> >       },
> >     },
> >   },
> > }
> > ```
> 
> is it wise to just ignore the error? The import points to a file which is not there... For something this import must be relevant or not?!

It's a typing error and those types get compiled away in the final app. Probably the real error is fixed when someone updates the graphql code generator plugin for graphql-request.

In my app, it seems like it works without any issues.

**Comment by saihaj** [comment]
released new version of GraphQL Request plugin here https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1684417928535

**Comment by LZL0** [comment]
@saihaj thank you! ❤️

**Comment by nbouvrette** [comment]
@saihaj I am missing something or does there stills need to be a new npm version released?

**Comment by saihaj** [comment]
> @saihaj I am missing something or does there stills need to be a new npm version released?

New version is released. See the release I linked

**Comment by nbouvrette** [comment]
@saihaj  I'm currently having this issue and those are the packages I use - none of them seems to have a new release.

```json
    "@graphql-codegen/cli": "3.3.1",
    "@graphql-codegen/introspection": "3.0.1",
    "@graphql-codegen/near-operation-file-preset": "2.5.0",
    "@graphql-codegen/typescript": "3.0.4",
    "@graphql-codegen/typescript-operations": "3.0.4",
    "@graphql-codegen/typescript-react-query": "4.1.0",
```

**Comment by mscharley** [comment]
I can find the updated packages, but it's still not quite working for me, probably because I'm using `"moduleResolution": "node16"` in my tsconfig and it's necessary in our project. I'm now getting this error instead:

```
src/generated/graphql/graphql-types.ts:6:50 - error TS2307: Cannot find module 'graphql-request/build/esm/types.js' or its corresponding type declarations.

6 import type { GraphQLClientRequestHeaders } from 'graphql-request/build/esm/types.js';
```

**Comment by mscharley** [comment]
It looks like you could alias it like this instead:

```typescript
import type { GraphQLClient, RequestOptions } from "graphql-request";
type GraphQLClientRequestHeaders = RequestOptions["requestHeaders"];
```

**Comment by nbouvrette** [comment]
@saihaj I just updated all my packages and run codegen and I am still getting generated files that include this:

<img width="858" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/6453322/9fcce672-6631-44dc-ba67-e5b9a1d3772b">

Based on my [previous comment](https://github.com/dotansimha/graphql-code-generator/issues/9046#issuecomment-1537242093) this seems to be a new issue related to TypeScript 5

Should I open a new issue on this specific topic instead?

**Comment by saihaj** [comment]
Yes that would be better

**Comment by khanakia** [comment]
I have updated all the packages to the latest and but issue has not been fixed
```
    "@graphql-codegen/cli": "4.0.0",
    "@graphql-codegen/typescript-operations": "^4.0.0",
    "@graphql-codegen/typescript-react-query": "^4.1.0",
 ```

**Comment by Angusross111** [comment]
Using the following package versions works correctly for me:
```
"dependencies": {
    "graphql": "16.6.0",
    "graphql-request": "6.1.0"
},
"devDependencies": {
    "@graphql-codegen/cli": "4.0.1",
    "@graphql-codegen/typescript": "4.0.0",
    "@graphql-codegen/typescript-graphql-request": "5.0.0",
    "@graphql-codegen/typescript-operations": "4.0.0",
    "@types/node": "18.16.16",
    "@types/react": "18.2.6",
    "typescript": "5.1.3"
}
```
Outputs:
```
import { GraphQLClient } from 'graphql-request';
import { GraphQLClientRequestHeaders } from 'graphql-request/build/cjs/types';
```
with no typescript errors

**Comment by maxpain** [comment]
Any updates?

**Comment by khanakia** [comment]
I do not think so. But i have fixed it for now like this which simply replace the line after code generation
```
  hooks: {
    afterAllFileWrite: ["sed -i '' '/types.dom/d' ./src/generated/graphql.ts"]
  }
```

**Comment by maxpain** [comment]
@khanakia in my case I have different import
<img width="1181" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/5875582/2a3dccc4-8dfe-4889-aa3d-250bc48e69a9">

**Comment by maxpain** [comment]
This error caused by "nodenext" module and moduleResolution fields in tsconfig.

**Comment by khanakia** [comment]
I see that the import is different because i am using `graphql-request` as fetcher so it does not adds the `GraphqQLClientRequestHeaders` import for me

**Comment by Xmaxer** [comment]
@maxpain Would you be able to share your tsconfig?

I changed mine from NodeNext -> Node16 and it is still throwing me the same error.

Related to more import issues, the GQL import of:

`import { gql } from 'graphql-tag';` doesn't seem to work for me. I get errors saying:

```
TS2349: This expression is not callable.   Type 'typeof import("/home/path/to/my/project/node_modules/graphql-tag/lib/index")' has no call signatures.
```

Until I manually change the import to:

`import { gql } from 'graphql-tag';` at which point it's no longer giving errors for the gql function.

**Comment by maxpain** [comment]
@Xmaxer 
```json
{
	"compilerOptions": {
		"outDir": ".build",
		"sourceMap": true,
		"composite": false,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"preserveSymlinks": true,
		"module": "nodenext",
		"moduleResolution": "nodenext",
		"target": "esnext",
		"lib": [
			"ESNext"
		],
		"incremental": true,
		"strict": true,
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,
		"noUncheckedIndexedAccess": true,
		"resolveJsonModule": true
	},
	"include": [
		"src/**/*.ts"
	]
}
```

**Comment by alex4brandung** [comment]
I don't know why this is closed? The issue is still present. The path to the types changes from 

`'graphql-request/dist/types.dom' `

to 

`'graphql-request/build/cjs/types.dom' `

when upgrading graphql-request version 5 to 6. So the code generator should adapt to those changes?! I  upgraded everything to the latest and the error still exists.

```json
"dependencies": {
    "graphql": "^16.7.1",
    "graphql-request": "6.1.0",
    "i18next": "^23.4.1",
    "next": "^13.4.12",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^5.0.0",
    "@graphql-codegen/typescript": "^4.0.1",
    "@graphql-codegen/typescript-operations": "^4.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",
    "typescript": "5.1.6"
  },
```

**Comment by davidhellmann** [comment]
same here :/

**Comment by james-butter** [comment]
Still experiencing this. Shouldn't be closed

**Comment by kbooz** [comment]
Facing same issue, had to downgrade to the same version of an old project:
```json
{
	"dependencies": {
		"graphql": "^16.4.0",
	    "graphql-config": "^5.0.1",
	    "graphql-request": "^4.2.0",
	    "graphql-tag": "^2.12.6"
	},
	"devDependencies": {
		"@graphql-codegen/add": "^4.0.1",
	    "@graphql-codegen/cli": "3.3.1",
	    "@graphql-codegen/import-types-preset": "^2.2.6",
	    "@graphql-codegen/typescript": "^3.0.4",
	    "@graphql-codegen/typescript-graphql-request": "^4.5.9",
	    "@graphql-codegen/typescript-operations": "^3.0.4",
	    "@graphql-codegen/typescript-resolvers": "^3.2.1",
	}
}
```

**Comment by davidhellmann** [comment]
Frustrating this topic. It would be great to get an update on how to solve the problem.

**Comment by aleczratiu** [comment]
Same for me

**Comment by locpt-oss** [comment]
For anyone who is still facing the problem, try this in `tsconfig.ts` add `typeRoots` and change `moduleResolution -> node`
```
"compilerOptions": {
    "typeRoots": ["./@types", "./node_modules/@types"],
    "moduleResolution": "node"
}
```

**Comment by aleczratiu** [comment]
I've tried by adding in tsconfig these rules but without any luck, the issue still persists. Thank you

**Comment by mastercoding** [comment]
For me this was resolved (as a temporary solution) by applying the following patch to the generated file:

```
--- api.ts	2023-09-07 17:02:50
+++ api2.ts	2023-09-07 17:03:02
@@ -1,5 +1,5 @@
-import { GraphQLClient } from 'graphql-request';
-import { GraphQLClientRequestHeaders } from 'graphql-request/build/cjs/types';
+import type { GraphQLClient } from 'graphql-request';
+import type { GraphQLClientRequestHeaders } from 'graphql-request/build/cjs/types';
 import gql from 'graphql-tag';
 export type Maybe<T> = T | null;
 export type InputMaybe<T> = Maybe<T>;
```

**Comment by hrmoller** [comment]
> For anyone who is still facing the problem, try this in `tsconfig.json` add `typeRoots` and change `moduleResolution -> node`. Hope it will help and happy coding
> 
> ```
> "compilerOptions": {
>     "typeRoots": ["./@types", "./node_modules/@types"],
>     "moduleResolution": "node"
> }
> ```

Just switching the `moduleResolution` to `node` in `tsconfig.json` seems to have fixed the issue in my case.

**Comment by Timeraa** [comment]
People who have this issue now, after fiddling around with the tsconfig, I found out that for me at least it is the option `verbatimModuleSyntax: true` which breaks the import, might be a TypeScript issue?

**Comment by diegotrrs** [comment]
I'm getting the same error. I'm sharing my hack here in case this is helpful to anybody.

Versions:
"@graphql-codegen/cli": "^5.0.0",
"@graphql-codegen/typescript": "^4.0.1",
"@graphql-codegen/typescript-graphql-request": "^5.0.0",
node: v18.17.1
"typescript": "5.2.2"

OS: Mac 13.3

Hook added in codegen.ts

```
hooks: {		
    afterOneFileWrite: ["sed -i '' -e '1s|.*|import type { GraphQLClient, RequestOptions } from \"graphql-request\";|' -e '2s|.*|type GraphQLClientRequestHeaders = RequestOptions[\"requestHeaders\"];|' src/lib/graphql/generated.ts"]
},
```
That replaces the first two lines with

```
import type { GraphQLClient, RequestOptions } from "graphql-request";
type GraphQLClientRequestHeaders = RequestOptions["requestHeaders"];
```

That might not be the solution for everybody.

**Comment by khanakia** [comment]
I use this code to replace
```
hooks: {
  afterAllFileWrite: ["sed -i '' '/types.dom/d' ./src/generated/graphql.ts"]
}
```

**Comment by tlmader** [comment]
Just upgraded to `"@graphql-codegen/typescript-graphql-request": "^6.0.0"` and issue still persists! 🥲

**Comment by bigfish** [comment]
Same problem

**Comment by ofurtumi** [comment]
i had the same problem but updated to `graphql-request@6.1.0` and to `@graphql-codegen/typescript-graphql-request@6.0.1` and now my project builds, don't even have to change the imports

**Comment by banool** [comment]
Still seeing this issue too with these deps:
```
    "graphql-request": "6.1.0",
    "@graphql-codegen/cli": "^5.0.0",
    "@graphql-codegen/import-types-preset": "^3.0.0",
    "@graphql-codegen/typescript": "^4.0.1",
    "@graphql-codegen/typescript-graphql-request": "^6.0.1",
    "@graphql-codegen/typescript-operations": "^4.0.1"
```

Changing the generated code from this:
```typescript
import { GraphQLClient } from 'graphql-request';
import { GraphQLClientRequestHeaders } from 'graphql-request/src/types.dom';
```

to this:
```typescript
import { GraphQLClient, RequestOptions } from 'graphql-request';
type GraphQLClientRequestHeaders = RequestOptions["requestHeaders"];
```

fixes it, as suggested by @diegotrrs.

**Comment by axelinternet** [comment]
I ran into this issue because of a version mismatch between `graphql-request` and the codegen packs. Updating correctly like @ofurtumi did solved it for me
