### ISSUE TITLE
Update @whatwg-node/fetch to avoid punycode deprecation warning in Node

### ISSUE THREAD

**Issue by daniel-nagy** [dotansimha/graphql-code-generator#9955]
### Is your feature request related to a problem? Please describe.

It looks like this package is using an old version of **@whatwg-node/fetch**. After upgrading to Node v22.0.0, I see warnings about punycode being deprecated. The source is graphql-codegen.

### Describe the solution you'd like

Upgrade **@whatwg-node/fetch** to the latest version.

### Is your feature request related to a problem? Please describe.

punycode is deprecated but used by old versions of **@whatwg-node/fetch**.

**Comment by ardatan** [comment]
Have you tried to update your lockfile?

**Comment by gblues** [comment]
This issue doesn't have anything to do with the lockfile.

Very simple reproduction steps:

1. Make an empty directory
2. run `node --version` and confirm node is version 22.0.0 or newer
3. run `npm init -y` to create package.json
4. run `npm install -D @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-resolvers`
5. run `npx graphql-code-generator init`

The punycode warning appears immediately:

```shell
npx graphql-code-generator init
(node:2916) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

This same warning appears when running `graphql-codegen`

**Comment by furai** [comment]
I think this actually breaks on node 22.4.x the watch mode when running codegen.

**Comment by formatlos** [comment]
Seeing the same issue

**Comment by deggertsen** [comment]
It looks like there is a dependency for @whatwg-node/fetch that is out of date which is depending on punycode. Perhaps all that is needed is to update that dependency?

**Comment by furai** [comment]
Can anything be done about it? It's currently stopping us from using watch mode as it breaks on node 22.x.

**Comment by franck-lynn** [comment]
same am I , 
npm ls punycode

+-- @graphql-codegen/cli@5.0.2
| `-- @whatwg-node/fetch@0.8.8
|   `-- @whatwg-node/node-fetch@0.3.6
|     `-- fast-url-parser@1.1.3
|       `-- punycode@1.4.1

it  looks like cause by  the dependency of  fast-url-parser@1.1.3

**Comment by deggertsen** [comment]
Here's the related fast-url-parser issue: https://github.com/petkaantonov/urlparser/issues/20

**Comment by deggertsen** [comment]
Ah, looking at the dependencies, it seems like @whatwg-node/fetch is using a different url parser (https://github.com/kamilkisiela/fast-url-parser) with its most recent version 0.9.20 but we're currently depending on 0.8.0. So, I think upgrading @whatwg-node/fetch is the right move here.

**Comment by avinashj-aa** [comment]
is there any update? is the codegen team going to release a new version with support for node 22 packages?

**Comment by avinashj-aa** [comment]
Is your feature request related to a problem? Please describe.
It looks like this package is using an old version of @whatwg-node/fetch. After upgrading to Node v22.0.0, I see warnings about punycode being deprecated. The source is graphql-codegen.

Describe the solution you'd like
Upgrade @whatwg-node/fetch to the latest version.

Describe alternatives you've considered
No response

Is your feature request related to a problem? Please describe.
punycode is deprecated but used by old versions of @whatwg-node/fetch.

**Comment by deggertsen** [comment]
Looks like this has been fixed in this commit https://github.com/dotansimha/graphql-code-generator/commit/e0092b548f51c95be19c232515cf9a72873e7b83
So now we're just waiting for a release!

**Comment by eddeee888** [comment]
Hi all, https://github.com/dotansimha/graphql-code-generator/pull/10076 has been merged so could you please check if the released versions work as expected?

**Comment by jay-l-e-e** [comment]
Any updates on this?

**Comment by keerthana-tw** [comment]
Bumping up discussion again. Is there any update on the issue? I still see errors and this is the dependency list I can see:
<img width="320" alt="image" src="https://github.com/user-attachments/assets/552e1b84-7cfb-4c62-80c0-e4a02d2f63f3" />

**Comment by eddeee888** [comment]
Hello! We are making a few changes to dependencies, will update here soon.

**Comment by dagadbm** [comment]
thank you! This comes just in time!

**Comment by eddeee888** [comment]
We found an old dependency in `@graphql-codegen/cli` that brings in `node-fetch@^2.6.11` which causes this issue. 
Most likely noone is using the old dependency, but we cannot deprecate it without release of a major version. 
I'm working towards releasing major version for some other packages at the moment, I may just group this one as well.

As far as I understand, this is only a warning - so it's not impacting the functionality of the program. Please let me know if that's not the case.

**Comment by furai** [comment]
For me it was segfaulting.

**Comment by eddeee888** [comment]
Are you able to share a reproducible repo @furai ? I'm happy to take a look to see what's causing the segfaulting.

**Comment by furai** [comment]
Unfortunately it's part of our live services and not something I can easily extract. It was segfaulting for me the first time I've encountered this issue long time ago. Currently I'm not sure and I have to recheck how it behaves. I'll try to get back to you on it if I'll find time.
